name: RegionalDialect
on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags
    branches:
      - '**'  # Triggers on all branches
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 
    container: docker.io/devkitpro/devkita64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: '0'

      - uses: lukka/get-cmake@latest

      - name: Build the project
        uses: lukka/run-cmake@v10
        with:
          configurePreset: Release
          buildPreset: Release

      - name: Create Github Artifact
        uses: actions/upload-artifact@v4.1.0
        with:
          name: subsdk9
          path: ${{ github.workspace }}/output/Release/subsdk9

      - name: Get Next Version
        id: getver
        uses: anothrNick/github-tag-action@v1
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags') || github.ref_name == 'master')
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TAG_PREFIX: v
          DEFAULT_BUMP: patch

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && ((startsWith(github.ref, 'refs/tags') || github.ref_name == 'master'))
        with:
          files: |
            ${{ github.workspace }}/output/Release/subsdk9

          tag_name: ${{ steps.getver.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
